### ISSUE TITLE
HSI超分问题

### ISSUE THREAD

**Issue by joyjoy2026** [jojolee6513/IPRSIG#1]
娇娇姐你好, 我叫陈壮, 是华中科技大学的一名研零学生, 最近我正在学习HSI超分问题, 并在诸多顶刊上看到了您发表的文章,  给我了很多启发并带来了很大的帮助, 非常感谢您做出的贡献. 但是由于我是初学者, 加上您的文章有些高深 所以有几个问题想向您请教下, 方便用邮件将您的联系方式发送给我吗,  我的邮箱是whut_chenzhuang@163.com, 如能回复不胜感激: )

**Comment by jojolee6513** [comment]
你是不是已经联系到学生了？
